<div class="fixed">
  <nav class="tab-bar header">
    <div class="left-small">
      <a href="#" class="left-off-canvas-toggle menu-icon"><span></span></a>
    </div>
    <div class="middle tab-bar-section">
      <div id="logo">
        <a href="index.shtml"><img src="img/AnarchyLOGO_mini.jpg" alt="Anarchy Logo"></a>
      </div>
    </div>
    <div class= "right">
      <p id="welcome"></p>
    </div>
  </nav>
  <nav class="navbar tab-bar">
    <div class="middle tab-bar-section navsection">
      <ul class="pagenav">
        <li><a href="index.shtml">Home</a></li>
        <li><a href="new.shtml">New</a></li>
        <li><a href="guys.shtml">Guys</a></li>
        <li><a href="girls.shtml">Girls</a></li>
        <li><a href="specials.shtml">Specials</a></li>
        <li><a href="contact.shtml">Contact</a></li>
      </ul>
    </div>
  </nav>
</div>